# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["hkakehashi+demo@fastly.com"]
description = "An empty starter kit project template."
language = "rust"
manifest_version = 2
name = "ws-frontend"
service_id = "4AULa2RBtJ1j2Qb72yfz8r"
